import type { Metadata, Viewport } from 'next';
import { Footer } from '@/components/modules/footer';
import { Header } from '@/components/modules/header';
import { Cursor } from '@/components/ui/motion/cursor';
import { JetBrains_Mono, Roboto } from 'next/font/google';
import '@/assets/styles/index.scss';

/* TODO: Разобраться с шрифтами в Next.js, почему они у меня кривые? */
/* motion для Next.js */

const fontJetbrainsMono = JetBrains_Mono({
   display: 'swap',
   weight: ['400', '700'],
   variable: '--font-jetbrains-mono',
   subsets: ['latin', 'cyrillic'],
   fallback: ['Verdana', 'Courier New', 'Courier'],
});

const fontRoboto = Roboto({
   weight: '400',
   display: 'swap',
   variable: '--font-roboto',
   subsets: ['latin', 'cyrillic'],
   fallback: ['Tahoma', 'Trebuchet MS', 'Arial'],
});

export const viewport: Viewport = {
   initialScale: 1,
   width: 1450,
   height: 900,
};

export const metadata: Metadata = {
   title: 'Victor Maznichenko✌️🤘',
   description: 'Generated by create next app',
};

function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="ru">
         <body
            className={`${fontJetbrainsMono.className} ${fontRoboto.variable}`}
         >
            <Header />
            <main className="main">{children}</main>
            <Footer />
            <Cursor />
         </body>
      </html>
   );
}

export default RootLayout;
